'use client';

import { Sparkles, Quote } from 'lucide-react';
import { cn } from '@/lib/utils';

interface NarrativeSummaryProps {
  text: string;
  variant?: 'default' | 'quote' | 'highlight';
  showAiBadge?: boolean;
  className?: string;
}

export function NarrativeSummary({
  text,
  variant = 'default',
  showAiBadge = true,
  className,
}: NarrativeSummaryProps) {
  if (variant === 'quote') {
    return (
      <div
        className={cn(
          'relative pl-4 py-2 border-l-2 border-primary/50',
          className
        )}
      >
        <Quote className="absolute -left-3 -top-1 h-6 w-6 text-primary/20" />
        <p className="text-sm italic text-muted-foreground">{text}</p>
        {showAiBadge && (
          <div className="flex items-center gap-1 mt-2">
            <Sparkles className="h-3 w-3 text-primary/60" />
            <span className="text-xs text-muted-foreground">AI Analysis</span>
          </div>
        )}
      </div>
    );
  }

  if (variant === 'highlight') {
    return (
      <div
        className={cn(
          'p-4 rounded-lg bg-gradient-to-r from-primary/5 to-primary/10 border border-primary/20',
          className
        )}
      >
        <div className="flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-primary shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium">{text}</p>
            {showAiBadge && (
              <span className="text-xs text-muted-foreground mt-1 block">
                Generated by AI analysis
              </span>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Default variant
  return (
    <div className={cn('flex items-start gap-2', className)}>
      {showAiBadge && (
        <Sparkles className="h-4 w-4 text-muted-foreground shrink-0 mt-0.5" />
      )}
      <p className="text-sm text-muted-foreground">{text}</p>
    </div>
  );
}

interface InsightQuoteProps {
  title: string;
  quote: string;
  source?: string;
  className?: string;
}

export function InsightQuote({ title, quote, source, className }: InsightQuoteProps) {
  return (
    <div
      className={cn(
        'p-4 rounded-lg bg-muted/50 border',
        className
      )}
    >
      <h4 className="text-sm font-semibold mb-2 flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-primary" />
        {title}
      </h4>
      <blockquote className="text-sm italic text-muted-foreground pl-3 border-l-2 border-primary/30">
        "{quote}"
      </blockquote>
      {source && (
        <p className="text-xs text-muted-foreground mt-2 text-right">
          — {source}
        </p>
      )}
    </div>
  );
}

export default NarrativeSummary;
